# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    assignees:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"
          - "pre-commit"
      web-dependencies:
        patterns:
          - "flask*"
          - "gunicorn"
          - "redis"
      ml-dependencies:
        patterns:
          - "torch*"
          - "transformers"
          - "faiss*"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    assignees:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    assignees:
      - "PatrickAllenCooper"  # Update with actual GitHub username
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope" 