# FM-LLM Solver - Main Configuration File
# 
# ⚠️ DEPRECATED: This file is being phased out in favor of hierarchical configuration
# 
# NEW CONFIGURATION SYSTEM:
# ========================
# The new hierarchical configuration system uses:
# 
# 1. config/base.yaml                    - Base configuration (all common settings)
# 2. config/environments/development.yaml - Development overrides
# 3. config/environments/staging.yaml     - Staging overrides  
# 4. config/environments/production.yaml  - Production overrides
# 5. config/user/local.yaml              - User-specific overrides (optional)
# 
# Usage:
# ------
# from utils.hierarchical_config_loader import load_hierarchical_config
# config = load_hierarchical_config()  # Auto-detects environment
# config = load_hierarchical_config(environment="production")
# 
# Environment Detection:
# ---------------------
# Set environment via:
# - FM_LLM_ENV=production
# - ENVIRONMENT=staging
# - NODE_ENV=development
# 
# Legacy Support:
# --------------
# For backward compatibility, this file imports from the hierarchical system:

# Import the new configuration system
import os
import sys
from pathlib import Path

# Add utils to path for import
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

try:
    from utils.hierarchical_config_loader import load_hierarchical_config
    
    # Load hierarchical configuration
    _config = load_hierarchical_config()
    
    # Export all configuration keys to this module's namespace for backward compatibility
    globals().update(_config)
    
    print("✅ Using new hierarchical configuration system")
    print(f"Environment: {_config['environment']['mode']}")
    print(f"Deployment: {_config['deployment']['mode']}")
    
except ImportError as e:
    print(f"⚠️ Could not load hierarchical config: {e}")
    print("Falling back to legacy configuration...")
    
    # Fallback to original configuration if hierarchical loader fails
    # This preserves backward compatibility during transition
    
    environment:
      mode: development
      debug: false
      log_level: INFO
      project_root: .
    
    database:
      url: sqlite:///instance/fmllm.db
      pool_size: 10
      max_overflow: 20
      pool_timeout: 30
      pool_recycle: 3600
      track_modifications: false
      echo: false
    
    web:
      host: "127.0.0.1"
      port: 5000
      csrf_enabled: true
      session_timeout: 3600
      max_content_length: 16777216
      enable_registration: true
      enable_api_keys: true
      default_subscription: basic
    
    inference:
      host: "127.0.0.1"
      port: 8000
      timeout: 300
      default_model: "base"
    
    deployment:
      mode: local
    
    # Note: This is a minimal fallback configuration
    # For full configuration, please use the hierarchical system
