name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["type/enhancement", "needs-triage"]
assignees: ["PatrickAllenCooper"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please provide as much detail as possible to help us understand and evaluate your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: I have read the project roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals and scope
          required: false

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: |
        As a [user type], I want [goal] so that [benefit].
        
        Current situation:
        - Issue/limitation you're facing
        - Why existing solutions don't work
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Detailed description of how you envision this feature working:
        - User interface changes
        - New functionality
        - Integration points
        - Expected behavior
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Web Interface
        - CLI Tools
        - Certificate Generation
        - Verification System
        - Knowledge Base
        - API
        - Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (Critical for my use case)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: |
        - Alternative approach A
        - Alternative approach B
        - Current workaround (if any)
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases and examples
      placeholder: |
        1. Use case 1: [Detailed scenario]
        2. Use case 2: [Detailed scenario]
        3. Use case 3: [Detailed scenario]
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How would you know this feature is complete and working correctly?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      render: markdown
    validations:
      required: false

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation thoughts
      placeholder: |
        - Performance implications
        - Security considerations
        - Backward compatibility
        - Dependencies
        - API changes
    validations:
      required: false

  - type: textarea
    id: ui_mockup
    attributes:
      label: UI/UX Mockup
      description: If this involves UI changes, provide mockups, wireframes, or descriptions
      placeholder: |
        - Screenshots of similar features
        - Wireframes or mockups
        - Detailed UI flow descriptions
    validations:
      required: false

  - type: dropdown
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - No breaking changes
        - Minor breaking changes (acceptable)
        - Major breaking changes (needs careful consideration)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, references, or information
      placeholder: |
        - Links to related research/papers
        - Similar features in other tools
        - Community feedback
        - Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I would like to work on implementing this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide domain expertise 