name: production
description: Production environment for live customer traffic

# Environment specific configurations
environment:
  name: production
  url: https://fm-llm-solver.com
  
# Deployment configurations
deployment:
  # Manual approval required for production
  auto_deploy: false
  
  # Strict approval requirements
  protection_rules:
    required_reviewers: 2
    wait_timer: 300  # 5 minutes
    deployment_branch_policy: "protected_branches"
    
  # Production environment variables
  variables:
    FLASK_ENV: production
    DEBUG: false
    LOG_LEVEL: WARNING
    
  # Production secrets (to be configured in GitHub repository settings)
  secrets:
    - KUBE_CONFIG_PROD
    - PROD_DATABASE_URL
    - PROD_REDIS_URL
    - SLACK_WEBHOOK
    - DATADOG_API_KEY
    - SENTRY_DSN
    - SSL_CERTIFICATE
    - SSL_PRIVATE_KEY
    
# Production resource configuration
resources:
  cpu_limit: "8"
  memory_limit: "16Gi"
  replicas: 3
  
  # Auto-scaling configuration
  autoscaling:
    min_replicas: 3
    max_replicas: 10
    cpu_target: 70%
    memory_target: 80%
    
# Comprehensive monitoring
monitoring:
  health_check_interval: 15s
  health_check_timeout: 5s
  health_check_retries: 5
  
  # Advanced monitoring
  apm_enabled: true
  metrics_collection: true
  log_aggregation: true
  distributed_tracing: true
  
  # Alerting thresholds
  alerts:
    error_rate_threshold: 0.5%
    response_time_p95_threshold: 1000ms
    cpu_threshold: 85%
    memory_threshold: 90%
    disk_threshold: 85%
    
# Comprehensive testing for production
testing:
  run_smoke_tests: true
  run_integration_tests: true
  run_performance_tests: true
  run_e2e_tests: true
  run_security_tests: true
  
  # Strict performance requirements
  performance_requirements:
    response_time_p95: 1000ms
    response_time_p99: 2000ms
    error_rate_max: 0.1%
    availability_min: 99.9%
    
# Blue-Green deployment configuration
deployment_strategy:
  type: "blue_green"
  traffic_split_percentage: 100
  canary_duration: "10m"
  health_check_grace_period: "2m"
  rollback_on_failure: true
  
# Backup and disaster recovery
backup:
  database_backup_schedule: "0 1,13 * * *"  # Twice daily
  retention_period: "30d"
  cross_region_backup: true
  
# Security requirements
security:
  vulnerability_scanning: true
  dependency_scanning: true
  secret_scanning: true
  code_scanning: true
  
  # Compliance requirements
  compliance_checks: ["SOC2", "GDPR", "CCPA"]
  
# Cleanup policy (conservative for production)
cleanup:
  retain_deployments: 20
  auto_cleanup_after_days: 30
  
# Maintenance windows
maintenance:
  allowed_windows:
    - day: "Sunday"
      time: "02:00-06:00"
      timezone: "UTC"
    - day: "Wednesday"
      time: "02:00-04:00"
      timezone: "UTC" 