name: staging
description: Staging environment for pre-production testing and QA

# Environment specific configurations
environment:
  name: staging
  url: https://staging.fm-llm-solver.com
  
# Deployment configurations
deployment:
  # Auto-deploy on push to staging branch
  auto_deploy: true
  
  # Approval required (minimal for staging)
  protection_rules:
    required_reviewers: 1
    wait_timer: 0
    
  # Environment variables
  variables:
    FLASK_ENV: staging
    DEBUG: false
    LOG_LEVEL: INFO
    
  # Secrets (to be configured in GitHub repository settings)
  secrets:
    - KUBE_CONFIG_STAGING
    - STAGING_DATABASE_URL
    - STAGING_REDIS_URL
    - SLACK_WEBHOOK
    
# Resource limits for staging (production-like)
resources:
  cpu_limit: "4"
  memory_limit: "8Gi"
  replicas: 2
  
# Monitoring settings
monitoring:
  health_check_interval: 30s
  health_check_timeout: 10s
  health_check_retries: 3
  
# Testing configuration
testing:
  run_smoke_tests: true
  run_integration_tests: true
  run_performance_tests: true
  run_e2e_tests: true
  
  # Performance testing thresholds
  performance_thresholds:
    response_time_p95: 2000ms
    error_rate_max: 1%
    cpu_utilization_max: 80%
    memory_utilization_max: 85%
    
# Cleanup policy
cleanup:
  retain_deployments: 10
  auto_cleanup_after_days: 14
  
# Data management
data:
  # Use production-like data but anonymized
  anonymize_data: true
  sync_from_production: true
  sync_schedule: "0 2 * * 1"  # Weekly on Monday 2 AM 