steps:
  # Build simplified web application
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.web.simple'
      - '-t'
      - 'us-central1-docker.pkg.dev/fmgen-net-production/fm-llm-repo/fm-llm-web-simple:${_IMAGE_TAG}'
      - '.'
    timeout: 600s

  # Push simplified web image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/fmgen-net-production/fm-llm-repo/fm-llm-web-simple:${_IMAGE_TAG}'
    timeout: 300s

substitutions:
  _IMAGE_TAG: 'latest'

timeout: 1200s 