apiVersion: v1
kind: ConfigMap
metadata:
  name: fm-llm-solver-config
  namespace: fm-llm-solver
  labels:
    app: fm-llm-solver
data:
  FM_LLM_ENV: "production"
  REDIS_URL: "redis://redis-service:6379/0"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fmllm"
  POSTGRES_USER: "fmllm"
  # Domain configuration
  DOMAIN_NAME: "fmgen.net"
  PRODUCTION_URL: "https://fmgen.net"
  STAGING_URL: "https://staging.fmgen.net"
  DEVELOPMENT_URL: "https://dev.fmgen.net"
  # Application configuration
  LOG_LEVEL: "INFO"
  CACHE_BACKEND: "redis"
  MONITORING_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"
  # Security settings
  RATE_LIMIT_DEFAULT: "100/day"
  RATE_LIMIT_API: "1000/hour"
  CORS_ENABLED: "true"
  CORS_ORIGINS: "https://fmgen.net,https://www.fmgen.net,https://staging.fmgen.net,https://dev.fmgen.net"
  SECURITY_HEADERS_ENABLED: "true"
  # Performance settings
  GUNICORN_WORKERS: "4"
  GUNICORN_TIMEOUT: "300"
  GUNICORN_KEEPALIVE: "2"
  GUNICORN_MAX_REQUESTS: "1000"
  GUNICORN_MAX_REQUESTS_JITTER: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fm-llm-solver-app-config
  namespace: fm-llm-solver
  labels:
    app: fm-llm-solver
data:
  config.yaml: |
    # Production configuration for FM-LLM-Solver
    # Domain: fmgen.net
    env_vars:
      MATHPIX_APP_ID: ''
      MATHPIX_APP_KEY: ''
      UNPAYWALL_EMAIL: ''
      SEMANTIC_SCHOLAR_API_KEY: ''
    
    huggingface:
      use_auth: false
      local_model_path: ''
    
    paths:
      project_root: /app
      data_dir: /app/data
      output_dir: /app/output
      kb_output_dir: /app/kb_data
      log_dir: /app/logs
    
    # Database configuration
    database:
      primary:
        host: "postgres-service"
        port: 5432
        database: "fmllm"
        username: "fmllm"
        password: "${secret:DB_PASSWORD}"
        pool_size: 20
        max_overflow: 10
        pool_timeout: 30
        pool_recycle: 3600
        ssl_mode: "prefer"
        echo: false
    
    # Cache configuration
    cache:
      backend: "redis"
      max_size: 10000
      default_ttl: 3600
      redis_url: "redis://redis-service:6379/0"
      redis_db: 0
      redis_max_connections: 20
      key_prefix: "fm_llm:"
      namespace: "production"
    
    # Logging configuration
    logging:
      log_directory: "/app/logs"
      root_level: "INFO"
      loggers:
        api:
          level: "INFO"
          handlers: ["console", "rotating_file"]
          json_format: true
          propagate: false
        model_operations:
          level: "INFO"
          handlers: ["console", "rotating_file"]
          json_format: true
          propagate: false
        security:
          level: "WARNING"
          handlers: ["console", "rotating_file"]
          json_format: true
          propagate: false
        database:
          level: "INFO"
          handlers: ["console", "rotating_file"]
          json_format: true
          propagate: false
    
    # Monitoring configuration
    monitoring:
      enabled: true
      metrics:
        prometheus_enabled: true
        custom_metrics_retention_hours: 24
        system_metrics_interval: 30
      health_checks:
        enabled: true
        default_interval: 30
        default_timeout: 10
        critical_failure_threshold: 3
      performance:
        slow_request_threshold: 5.0
        memory_usage_threshold: 90
        cpu_usage_threshold: 90
    
    # Security configuration
    security:
      rate_limit:
        default: "100/day"
        api_endpoints: "1000/hour"
        auth_endpoints: "10/minute"
      cors:
        enabled: true
        origins: ["https://fmgen.net", "https://www.fmgen.net", "https://staging.fmgen.net", "https://dev.fmgen.net"]
        max_age: 86400
      headers:
        force_https: true
        content_security_policy: true
        frame_options: "DENY"
      session:
        timeout_minutes: 1440
        secure_cookies: true
    
    # Web interface configuration
    web_interface:
      host: "0.0.0.0"
      port: 5000
      debug: false
      cors_origins: ["https://fmgen.net", "https://www.fmgen.net", "https://staging.fmgen.net", "https://dev.fmgen.net"]
      base_url: "https://fmgen.net"
    
    # Fine-tuning configuration
    fine_tuning:
      base_model_name: "Qwen/Qwen2.5-14B-Instruct"
      data_format: instruction
      use_adapter: true
      quantization:
        use_4bit: true
        bnb_4bit_compute_dtype: float16
        bnb_4bit_quant_type: nf4
        use_nested_quant: true
      training:
        num_train_epochs: 1
        per_device_train_batch_size: 1
        gradient_accumulation_steps: 8
        gradient_checkpointing: true
        max_grad_norm: 0.3
        learning_rate: 0.0002
        weight_decay: 0.001
        max_seq_length: 1024
    
    # Inference configuration
    inference:
      rag_k: 3
      max_new_tokens: 200
      temperature: 0.3
      top_p: 0.85
      device: "auto"
      torch_dtype: "auto"
      do_sample: true
      repetition_penalty: 1.1 