apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fm-llm-gke-ingress
  namespace: fm-llm-solver
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "fm-llm-static-ip-west"
    networking.gke.io/managed-certificates: "fmgen-ssl-cert"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: fmgen.net
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: fm-llm-web-hybrid-fixed-service
            port:
              number: 80
  - host: www.fmgen.net
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: fm-llm-web-hybrid-fixed-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: fmgen-ssl-cert
  namespace: fm-llm-solver
spec:
  domains:
  - fmgen.net
  - www.fmgen.net 