apiVersion: v1
kind: Namespace
metadata:
  name: fm-llm-solver
  labels:
    name: fm-llm-solver
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-llm-solver
  namespace: fm-llm-solver
  labels:
    app: fm-llm-solver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fm-llm-solver
  name: fm-llm-solver-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fm-llm-solver-rolebinding
  namespace: fm-llm-solver
subjects:
- kind: ServiceAccount
  name: fm-llm-solver
  namespace: fm-llm-solver
roleRef:
  kind: Role
  name: fm-llm-solver-role
  apiGroup: rbac.authorization.k8s.io 