apiVersion: v1
kind: Secret
metadata:
  name: fm-llm-solver-secrets
  namespace: fm-llm-solver
  labels:
    app: fm-llm-solver
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "changeme-in-production"
  POSTGRES_PASSWORD: "changeme-in-production"
  
  # Application secrets
  SECRET_KEY: "change-this-secret-key-in-production"
  ENCRYPTION_KEY: "change-this-encryption-key-in-production"
  
  # External API keys (optional)
  MATHPIX_APP_ID: ""
  MATHPIX_APP_KEY: ""
  UNPAYWALL_EMAIL: ""
  SEMANTIC_SCHOLAR_API_KEY: ""
  
  # JWT secrets
  JWT_SECRET_KEY: "change-this-jwt-secret-in-production"
  
  # External service credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AZURE_CLIENT_ID: ""
  AZURE_CLIENT_SECRET: ""
  
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: fm-llm-solver
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "fmllm"
  POSTGRES_PASSWORD: "changeme-in-production"
  POSTGRES_DB: "fmllm"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: fm-llm-solver
  labels:
    app: redis
type: Opaque
stringData:
  REDIS_PASSWORD: "changeme-in-production" 