# FM-LLM Solver - Development Environment Overrides
# This file only contains settings that differ from base.yaml for development

# ============================================================================
# Environment Settings (Development Overrides)
# ============================================================================
environment:
  mode: development
  debug: true
  log_level: DEBUG

# ============================================================================
# Database (Development - SQLite with debugging)
# ============================================================================
database:
  url: "sqlite:///instance/fmllm_dev.db"
  echo: true  # Show SQL queries in development

# ============================================================================
# Cache (Development - Optional Redis)
# ============================================================================
cache:
  enabled: false  # Disable cache for development to see real-time changes
  url: "redis://localhost:6379/1"  # Different DB from production

# ============================================================================
# Web Interface (Development - Relaxed Security)
# ============================================================================
web:
  host: "127.0.0.1"
  port: 5000
  
  # Relaxed security for development
  csrf_enabled: false  # Easier testing
  session_timeout: 86400  # 24 hours
  max_content_length: 104857600  # 100MB for testing
  
  # Open registration for development
  enable_registration: true
  enable_api_keys: true
  default_subscription: enterprise  # Full access for testing
  
  # Relaxed rate limiting for development
  rate_limit:
    enabled: false  # No rate limiting in dev
    default: "1000 per hour"
    api: "10000 per hour"
    burst: "100 per minute"

# ============================================================================
# Inference (Development - Local with debugging)
# ============================================================================
inference:
  host: "127.0.0.1"
  port: 8000
  timeout: 600  # Longer timeout for debugging

# ============================================================================
# Models (Development - Smaller/faster models)
# ============================================================================
models:
  base:
    # Use smaller model for faster development iteration
    name: "Qwen/Qwen2.5-7B-Instruct"
    max_new_tokens: 256  # Shorter for faster generation
    temperature: 0.2     # Slightly higher for variety in testing

# ============================================================================
# Performance (Development - Conservative settings)
# ============================================================================
performance:
  cuda:
    visible_devices: "0"
    memory_config: "max_split_size_mb:256"  # Conservative for development
  
  cpu_workers: 2  # Lower for development
  max_memory: 8   # Conservative memory usage
  
  model_cache_size: 1  # Keep only one model in memory

# ============================================================================
# Deployment (Development - Local mode)
# ============================================================================
deployment:
  mode: local  # Always local for development
  
  services:
    web:
      workers: 1
    inference:
      workers: 1

# ============================================================================
# Development-Specific Features
# ============================================================================
development:
  # Auto-reload settings
  auto_reload: true
  
  # Testing
  test_database_url: "sqlite:///test.db"
  test_timeout: 60
  
  # Debug features
  enable_sql_echo: true
  enable_profiling: true
  mock_external_apis: true  # Mock APIs for offline development

# ============================================================================
# Feature Flags (Development - Enable experimental features)
# ============================================================================
features:
  # Enable all experimental features for testing
  enable_conversation_mode: true
  enable_batch_processing: true
  enable_model_comparison: true
  enable_verification_service: true
  enable_dark_mode: true
  enable_advanced_settings: true 